<?php
function don_hang_menu()
{
    $items['them-don-hang'] = array(
        'title' => '',
        'delivery callback' => 'them_don_hang',
        'access callback' => 'TRUE',
        'access arguments' => array('them_don_hang'),
        'type' => MENU_CALLBACK
    );
    $items['quan-li-tinh-trang-don-hang'] = array(
        'title' => '',
        'delivery callback' => 'sua_tinh_trang_don_hang',
        'access callback' => 'TRUE',
        'access arguments' => array('sua_tinh_trang_don_hang'),
        'type' => MENU_CALLBACK
    );
    return $items;
}

function them_don_hang(){
    $ho_ten = $_POST['ho_ten'];
    $phone = $_POST['phone'];
    $thanh_pho = $_POST['thanh_pho'];
    $quan_huyen = $_POST['quan_huyen'];
    $phuong_xa = $_POST['phuong_xa'];
    $dia_chi_chi_tiet = $_POST['dia_chi_chi_tiet'];
    $ghi_chu = $_POST['ghi_chu'];
    $ma_giam_gia = $_POST['ma_giam_gia'];
    $price = intval($_POST['price']);
    $dich_vu = $_POST['dich_vu'];
    $newnode = array(
        'type' => 'don_hang',
        'language' => 'vi',
        'status' => 1,
        'comment' => 0,
        'uid'=>1,
        'promote' => 0,
        'title' => $ho_ten
    );
    $khoitaonode=entity_create('node',$newnode);
    $truyva=entity_metadata_wrapper('node',$khoitaonode);
    $truyva->field_so_dien_thoai->set($phone);
    $truyva->field_dia_chi->set($dia_chi_chi_tiet);
    $truyva->field_thanh_pho->set($thanh_pho);
    $truyva->field_quan_huyen->set($quan_huyen);
    $truyva->field_phuong_xa->set($phuong_xa);
    $truyva->field_ho_ten->set($ho_ten);
    $truyva->field_ghi_chu->set($ghi_chu);
    $truyva->field_ma_gioi_thieu->set($ma_giam_gia);
    $truyva->field_gia->set($price);
    $truyva->field_cu_phap->set($dich_vu);
    $truyva->field_tinh_trang_don_hang->set('dang_treo');
    $ktra=$truyva->save();
    if ($ktra){
        dpm('Thêm thành công');
    }else{
        drupal_set_message('Lỗi không thêm được','error');
    }
}
function sua_tinh_trang_don_hang(){
    if (isset($_POST['nid'])){
        $state_order = $_POST['state_order'];
        $node = node_load($_POST['nid']);
        $query = entity_metadata_wrapper('node',$node);
        $query->field_tinh_trang_don_hang->set($state_order);
        $check = $query->save();
        if ($check){

        }else{
            drupal_set_message('Lỗi không thêm được','error');
        }
    }
}
function don_hang_permission() {
    return array(
        'them_don_hang'=>array(
            'title'=>'Thêm đơn hàng',
        ),
        'sua_tinh_trang_don_hang'=>array(
            'title'=>'Sửa tình trạng đơn hàng',
        ),
    );
}

